name: example
description: An example app for cupertino_menu.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.0.0
dependencies:
  cupertino_icons: ^1.0.8
  cupertino_menu:
    path: ..
  flutter:
    sdk: flutter
  flutter_portal: ^1.1.4
  simple_logger: ^1.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
  uses-material-design: true
