name: cupertino_menu
description: TODO
version: 0.0.1
homepage: https://github.com/mono0926/cupertino_menu
environment:
  sdk: ">=2.5.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  simple_logger: ^1.7.0
  meta: ^1.1.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
