name: cupertino_menu
description: An iOS 14 style Cupertino popup menu button widget powered by flutter_portal.
version: 0.0.3+5
homepage: https://github.com/mono0926/cupertino_menu
environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_portal: ^1.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:

